from __future__ import annotations

from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.access_control import can_view_media, get_person_access
from app.models.book import BookProject
from app.models.media import Media
from app.models.person import Person
from app.models.story import Story
from app.services.media_service import get_media_file_path
from app.services.timeline_service import get_timeline_events


async def build_book_export(
    db: AsyncSession,
    *,
    project: BookProject,
    actor: Person,
) -> tuple[str, bytes]:
    people = []
    for person_id in project.person_ids:
        person = await db.get(Person, person_id)
        if person is None:
            continue
        access = await get_person_access(db, actor, person)
        if not access.can_view:
            continue
        people.append(person)

    story_result = await db.execute(
        select(Story).where(Story.id.in_(project.story_ids)).order_by(Story.created_at.asc())
    )
    stories = []
    for story in story_result.scalars().all():
        person = await db.get(Person, story.person_id)
        if person is None:
            continue
        access = await get_person_access(db, actor, person)
        if not access.can_view:
            continue
        stories.append((story, person))

    media_result = await db.execute(
        select(Media).where(Media.id.in_(project.media_ids)).order_by(Media.created_at.asc())
    )
    media_items = []
    for media in media_result.scalars().all():
        if not await can_view_media(db, actor, media):
            continue
        person = await db.get(Person, media.person_id)
        media_items.append((media, person))

    timeline_events = []
    if project.include_timeline:
        timeline_events, _ = await get_timeline_events(db, actor, limit=20)

    markdown = _render_markdown(project, people, stories, media_items, timeline_events)
    pdf_bytes = _render_simple_pdf(markdown)
    return markdown, pdf_bytes


def _render_markdown(
    project: BookProject,
    people: list[Person],
    stories: list[tuple[Story, Person]],
    media_items: list[tuple[Media, Person | None]],
    timeline_events: list[dict],
) -> str:
    lines = [
        f"# {project.title}",
        "",
    ]
    if project.subtitle:
        lines.extend([project.subtitle, ""])
    if project.introduction:
        lines.extend([project.introduction, ""])

    lines.extend(["## Table of Contents", ""])
    lines.append("- People")
    if stories:
        lines.append("- Stories")
    if media_items:
        lines.append("- Media")
    if timeline_events:
        lines.append("- Timeline")
    lines.append("")

    lines.extend(["## People", ""])
    for person in people:
        lines.append(f"### {person.display_name}")
        if person.birth_date:
            lines.append(f"- Born: {person.birth_date}")
        if person.birth_place:
            lines.append(f"- Birth place: {person.birth_place}")
        if person.bio:
            lines.extend(["", person.bio, ""])
        if person.source_detail:
            lines.append(f"- Source note: {person.source_detail}")
        lines.append("")

    if stories:
        lines.extend(["## Stories", ""])
        for story, person in stories:
            lines.append(f"### {story.title}")
            lines.append(f"*For {person.display_name}*")
            lines.append("")
            lines.append(story.body.strip() or "_No story text provided._")
            if story.source:
                lines.extend(["", f"Source: {story.source}"])
            lines.append("")

    if media_items:
        lines.extend(["## Media", ""])
        for media, person in media_items:
            title = media.title or media.caption or media.original_filename or media.id
            owner = person.display_name if person else "Unknown person"
            lines.append(f"- **{title}** ({owner})")
            if media.description:
                lines.append(f"  - {media.description}")
            if media.taken_date:
                lines.append(f"  - Taken: {media.taken_date}")
            if media.file_path:
                file_path = get_media_file_path(media.file_path)
                if file_path:
                    lines.append(f"  - File: {file_path}")
        lines.append("")

    if timeline_events:
        lines.extend(["## Timeline", ""])
        for event in timeline_events:
            lines.append(f"- {event['date']}: {event['label']}")
        lines.append("")

    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines.extend(["---", f"Generated by Family Book on {generated_at}"])
    return "\n".join(lines).strip() + "\n"


def _render_simple_pdf(markdown: str) -> bytes:
    lines = markdown.splitlines()
    pages = []
    chunk_size = 40
    for index in range(0, len(lines), chunk_size):
        pages.append(lines[index:index + chunk_size])

    objects = []

    def add_object(payload: str) -> int:
        objects.append(payload)
        return len(objects)

    font_id = add_object("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    page_ids = []
    content_ids = []

    for page_lines in pages or [["Family Book export"]]:
        stream_lines = ["BT", f"/F1 12 Tf", "50 780 Td", "14 TL"]
        first = True
        for line in page_lines:
            escaped = (
                line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
            )
            if not first:
                stream_lines.append("T*")
            stream_lines.append(f"({escaped[:110]}) Tj")
            first = False
        stream_lines.append("ET")
        stream = "\n".join(stream_lines).encode("latin-1", errors="replace")
        content_id = add_object(
            f"<< /Length {len(stream)} >>\nstream\n{stream.decode('latin-1')}\nendstream"
        )
        content_ids.append(content_id)
        page_id = add_object(
            f"<< /Type /Page /Parent PAGES_REF /MediaBox [0 0 612 792] "
            f"/Resources << /Font << /F1 {font_id} 0 R >> >> "
            f"/Contents {content_id} 0 R >>"
        )
        page_ids.append(page_id)

    kids = " ".join(f"{page_id} 0 R" for page_id in page_ids)
    pages_id = add_object(f"<< /Type /Pages /Count {len(page_ids)} /Kids [{kids}] >>")
    catalog_id = add_object(f"<< /Type /Catalog /Pages {pages_id} 0 R >>")

    final_objects = []
    for payload in objects:
        final_objects.append(payload.replace("PAGES_REF", f"{pages_id} 0 R"))

    pdf = ["%PDF-1.4\n"]
    offsets = []
    for index, payload in enumerate(final_objects, start=1):
        offsets.append(sum(len(part.encode("latin-1")) for part in pdf))
        pdf.append(f"{index} 0 obj\n{payload}\nendobj\n")
    xref_offset = sum(len(part.encode("latin-1")) for part in pdf)
    pdf.append(f"xref\n0 {len(final_objects) + 1}\n")
    pdf.append("0000000000 65535 f \n")
    for offset in offsets:
        pdf.append(f"{offset:010d} 00000 n \n")
    pdf.append(
        f"trailer\n<< /Size {len(final_objects) + 1} /Root {catalog_id} 0 R >>\n"
        f"startxref\n{xref_offset}\n%%EOF"
    )
    return "".join(pdf).encode("latin-1", errors="replace")
