from __future__ import annotations

import hashlib
from functools import lru_cache

from cryptography.fernet import Fernet, InvalidToken

from app.config import get_settings

ENCRYPTED_PREFIX = "enc::"
PROTECTED_PERSON_FIELDS = [
    "medical_history",
    "contact_whatsapp",
    "contact_telegram",
    "contact_signal",
    "contact_email",
]


class ProtectionConfigurationError(RuntimeError):
    pass


class ProtectedFieldDecryptionError(RuntimeError):
    pass


def normalize_email_for_lookup(value: str | None) -> str | None:
    if value is None:
        return None
    normalized = value.strip().lower()
    return normalized or None


def contact_email_lookup_hash(value: str | None) -> str | None:
    normalized = normalize_email_for_lookup(value)
    if not normalized:
        return None
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


@lru_cache(maxsize=8)
def _normalized_fernet_key(raw_key: str) -> bytes:
    candidate = raw_key.strip().encode("utf-8")
    try:
        Fernet(candidate)
        return candidate
    except Exception as exc:
        raise ProtectionConfigurationError(
            "FERNET_KEY must be a valid Fernet key generated by cryptography.fernet.Fernet.generate_key()."
        ) from exc


def is_valid_fernet_key(raw_key: str | None) -> bool:
    if not raw_key:
        return False
    try:
        _normalized_fernet_key(raw_key)
        return True
    except ProtectionConfigurationError:
        return False


def get_fernet() -> Fernet:
    settings = get_settings()
    return Fernet(_normalized_fernet_key(settings.FERNET_KEY))


def encrypt_string(value: str | None) -> str | None:
    if value is None:
        return None
    if value.startswith(ENCRYPTED_PREFIX):
        return value
    token = get_fernet().encrypt(value.encode("utf-8")).decode("utf-8")
    return f"{ENCRYPTED_PREFIX}{token}"


def decrypt_string(value: str | None) -> str | None:
    if value is None:
        return None
    if not value.startswith(ENCRYPTED_PREFIX):
        return value
    token = value[len(ENCRYPTED_PREFIX):].encode("utf-8")
    try:
        return get_fernet().decrypt(token).decode("utf-8")
    except InvalidToken as exc:
        raise ProtectedFieldDecryptionError(
            "Unable to decrypt protected data with the configured FERNET_KEY."
        ) from exc


def encrypt_mapping_fields(snapshot: dict, fields: list[str]) -> dict:
    protected = dict(snapshot)
    for field in fields:
        if field in protected:
            protected[field] = encrypt_string(protected[field])
    return protected


def decrypt_mapping_fields(snapshot: dict, fields: list[str]) -> dict:
    unprotected = dict(snapshot)
    for field in fields:
        if field in unprotected:
            unprotected[field] = decrypt_string(unprotected[field])
    return unprotected


def get_protection_contract() -> dict:
    settings = get_settings()
    data_dir = getattr(settings, "resolved_data_dir", getattr(settings, "DATA_DIR", "data"))
    key_valid = is_valid_fernet_key(getattr(settings, "FERNET_KEY", None))
    return {
        "field_encryption_enabled": key_valid,
        "fernet_key_valid": key_valid,
        "protected_person_fields": PROTECTED_PERSON_FIELDS,
        "transport_security": "HTTPS is required at deployment edge; cookies are marked secure when BASE_URL is https.",
        "storage_contract": (
            f"SQLite data, media, and backups are expected under {data_dir}. "
            "Field-level encryption protects direct-contact and medical fields in application storage."
        ),
        "notes": [
            "Field-level encryption is application-managed, not client-side end-to-end encryption.",
            "Backups preserve encrypted field values and must be protected as private family data.",
        ],
    }
