"""add_saved_records_table

Revision ID: 08f77a386981
Revises: b919e1b33636
Create Date: 2026-03-26 15:58:18.107170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f77a386981'
down_revision: Union[str, Sequence[str], None] = 'b919e1b33636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('date_found', sa.String(length=20), nullable=True),
    sa.Column('saved_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['saved_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_records_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_records_person_id'))

    op.drop_table('saved_records')
    # ### end Alembic commands ###
