"""add_life_story_fields

Revision ID: 91c60b8a16f9
Revises: f4d31ae6fded
Create Date: 2026-03-25 22:20:12.411588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c60b8a16f9'
down_revision: Union[str, Sequence[str], None] = 'f4d31ae6fded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obituary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('obituary_source', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('career', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('organizations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('organizations')
        batch_op.drop_column('career')
        batch_op.drop_column('education')
        batch_op.drop_column('obituary_source')
        batch_op.drop_column('obituary')

    # ### end Alembic commands ###
