"""add_source_citation_confidence_and_media_purpose

Revision ID: 9e0aa75cb010
Revises: 9dc8ffc2dc25
Create Date: 2026-03-26 13:22:09.773107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0aa75cb010'
down_revision: Union[str, Sequence[str], None] = '9dc8ffc2dc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=20), nullable=True))

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_detail', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('confidence')
        batch_op.drop_column('source_detail')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
