"""drop_moments_tables

Revision ID: b48cf4579cfc
Revises: 08f77a386981
Create Date: 2026-03-26 19:56:27.211201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48cf4579cfc'
down_revision: Union[str, Sequence[str], None] = '08f77a386981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moment_reactions')
    op.drop_table('moment_comments')
    op.drop_table('moments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moment_comments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('moment_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('person_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('body', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['moment_id'], ['moments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('person_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=20), nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('media_ids', sa.TEXT(), nullable=True),
    sa.Column('milestone_type', sa.VARCHAR(length=30), nullable=True),
    sa.Column('occurred_at', sa.DATETIME(), nullable=False),
    sa.Column('occurred_precision', sa.VARCHAR(length=10), nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), nullable=False),
    sa.Column('visibility', sa.VARCHAR(length=20), nullable=False),
    sa.Column('posted_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('tagged_person_ids', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('lifecycle_state', sa.VARCHAR(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('moderated_at', sa.DATETIME(), nullable=True),
    sa.Column('moderated_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('moderation_reason', sa.VARCHAR(length=500), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moment_reactions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('moment_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('person_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['moment_id'], ['moments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moment_id', 'person_id', name=op.f('uq_reaction_per_person'))
    )
    # ### end Alembic commands ###
