"""add last_login_at and invite delivery columns

Revision ID: db5ef4013c09
Revises: d60183d4b818
Create Date: 2026-03-31 17:57:40.646429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5ef4013c09'
down_revision: Union[str, Sequence[str], None] = 'd60183d4b818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_error', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('delivery_message_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sent_at', sa.String(length=40), nullable=True))

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('sent_at')
        batch_op.drop_column('delivery_message_id')
        batch_op.drop_column('delivery_error')
        batch_op.drop_column('delivery_status')

    # ### end Alembic commands ###
