"""add gedcom import batch table

Revision ID: f4d31ae6fded
Revises: 74a687671a40
Create Date: 2026-03-25 21:07:25.343622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d31ae6fded'
down_revision: Union[str, Sequence[str], None] = '74a687671a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gedcom_import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('persons_created', sa.Integer(), nullable=False),
    sa.Column('relationships_created', sa.Integer(), nullable=False),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=False),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('imported_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gedcom_import_batches')
    # ### end Alembic commands ###
